# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Joseph Cunningham
email: joeywas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My catchy blog description would go here, but i'm not feeling catchy!
  I'm mostly a literal guy, so what you will see here is going to be just me. 
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://joeywas.github.io" # the base hostname & protocol for your site
twitter_username: joseph_c
github_username:  joeywas

# Build settings
#markdown: kramdown
theme: minima
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md